/* eslint-disable */
/* oxlint-disable */
// Auto-generated by @contentrain/query — do not edit manually

const _defaultLocale = 'en'

import _auditEventEn from './data/audit-event.en.mjs'
import _billingPlanEn from './data/billing-plan.en.mjs'
import _dashboardOverviewEn from './data/dashboard-overview.en.mjs'
import _dashboardStatEn from './data/dashboard-stat.en.mjs'
import _footerEn from './data/footer.en.mjs'
import _navigationEn from './data/navigation.en.mjs'
import _opsNoticeEn from './data/ops-notice.en.mjs'
import _seoDefaultsEn from './data/seo-defaults.en.mjs'
import _settingsGroupEn from './data/settings-group.en.mjs'
import _siteSettingsEn from './data/site-settings.en.mjs'
import _uiCopyEn from './data/ui-copy.en.mjs'
import _workQueueItemEn from './data/work-queue-item.en.mjs'

// ─── Runtime Classes ───

class QueryBuilder {
  constructor(data, relationMeta, resolver, defaultLocale) { this._data = data; this._filters = []; this._sortField = null; this._sortOrder = 'asc'; this._limit = null; this._offset = 0; this._locale = null; this._includes = []; this._relationMeta = relationMeta || {}; this._resolver = resolver || null; this._defaultLocale = defaultLocale || null; }
  locale(lang) { this._locale = lang; return this; }
  where(field, value) { this._filters.push(item => { const v = item[field]; return Array.isArray(v) ? v.includes(value) : v === value; }); return this; }
  sort(field, order = 'asc') { this._sortField = field; this._sortOrder = order; return this; }
  limit(n) { this._limit = n; return this; }
  offset(n) { this._offset = n; return this; }
  include(...fields) { this._includes.push(...fields); return this; }
  all() {
    let items; if (this._locale) { items = [...(this._data.get(this._locale) ?? [])]; } else if (this._defaultLocale && this._data.has(this._defaultLocale)) { items = [...this._data.get(this._defaultLocale)]; } else { items = [...(this._data.get(this._data.keys().next().value) ?? [])]; }
    for (const f of this._filters) items = items.filter(f);
    if (this._sortField) { const sf = this._sortField; const d = this._sortOrder === 'asc' ? 1 : -1; items.sort((a, b) => { const va = a[sf], vb = b[sf]; if (va == null && vb == null) return 0; if (va == null) return d; if (vb == null) return -d; return va < vb ? -d : va > vb ? d : 0; }); }
    if (this._offset > 0 || this._limit !== null) { const end = this._limit !== null ? this._offset + this._limit : undefined; items = items.slice(this._offset, end); }
    if (this._includes.length > 0 && this._resolver) { items = items.map(item => this._resolveIncludes(item)); }
    return items;
  }
  first() { return this.all()[0]; }
  _resolveIncludes(item) {
    const resolved = { ...item };
    for (const field of this._includes) {
      const meta = this._relationMeta[field]; if (!meta) continue;
      const targets = Array.isArray(meta.target) ? meta.target : [meta.target];
      if (meta.multi) { const ids = item[field]; if (Array.isArray(ids)) { resolved[field] = ids.map(id => { if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, this._locale); if (r) return r; } return id; } if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, this._locale); if (r) return r; } return id; }); } }
      else { const id = item[field]; if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, this._locale); if (r) { resolved[field] = r; break; } } } else if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, this._locale); if (r) resolved[field] = r; } }
    }
    return resolved;
  }
}

class SingletonAccessor {
  constructor(data, defaultLocale, relationMeta, resolveEntry) { this._data = data; this._locale = null; this._defaultLocale = defaultLocale || null; this._includes = []; this._relationMeta = relationMeta || {}; this._resolver = resolveEntry; }
  locale(lang) { this._locale = lang; return this; }
  include(...fields) { this._includes.push(...fields); return this; }
  get() {
    const locale = this._locale || this._defaultLocale;
    let d = locale ? this._data.get(locale) : undefined;
    if (!d) { const key = this._data.keys().next().value; d = key !== undefined ? this._data.get(key) : undefined; }
    if (!d) throw new Error('No data available');
    if (this._includes.length > 0 && this._resolver) return this._resolveIncludes(d, locale || 'en');
    return d;
  }
  _resolveIncludes(item, locale) {
    const resolved = { ...item };
    for (const field of this._includes) {
      const meta = this._relationMeta[field]; if (!meta) continue;
      const targets = Array.isArray(meta.target) ? meta.target : [meta.target];
      if (meta.multi) { const ids = item[field]; if (Array.isArray(ids)) { resolved[field] = ids.map(id => { if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, locale); if (r) return r; } return id; } if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, locale); if (r) return r; } return id; }); } }
      else { const id = item[field]; if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, locale); if (r) { resolved[field] = r; break; } } } else if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, locale); if (r) resolved[field] = r; } }
    }
    return resolved;
  }
}

class DictionaryAccessor {
  constructor(data, defaultLocale) { this._data = data; this._locale = null; this._defaultLocale = defaultLocale || null; }
  locale(lang) { this._locale = lang; return this; }
  get(key, params) {
    let dict; if (this._locale) { dict = this._data.get(this._locale) ?? {}; } else if (this._defaultLocale && this._data.has(this._defaultLocale)) { dict = this._data.get(this._defaultLocale); } else { const loc = this._data.keys().next().value; dict = this._data.get(loc) ?? {}; }
    if (key === undefined) return dict;
    const val = dict[key];
    if (val === undefined) return undefined;
    if (params) return val.replace(/{(w+)}/g, (m, k) => { const v = params[k]; return v !== undefined ? String(v) : m; });
    return val;
  }
}

class DocumentQuery {
  constructor(data, relationMeta, resolver, defaultLocale) { this._data = data; this._filters = []; this._locale = null; this._includes = []; this._relationMeta = relationMeta || {}; this._resolver = resolver || null; this._defaultLocale = defaultLocale || null; }
  locale(lang) { this._locale = lang; return this; }
  where(field, value) { this._filters.push(item => item[field] === value); return this; }
  include(...fields) { this._includes.push(...fields); return this; }
  bySlug(slug) {
    const items = this._resolveData(); const item = items.find(x => x.slug === slug);
    if (item && this._includes.length > 0 && this._resolver) return this._resolveIncludes(item);
    return item;
  }
  first() { return this.all()[0]; }
  all() { let items = this._resolveData(); for (const f of this._filters) items = items.filter(f); if (this._includes.length > 0 && this._resolver) { items = items.map(item => this._resolveIncludes(item)); } return items; }
  _resolveData() { let key; if (this._locale) { key = this._locale; } else if (this._defaultLocale && this._data.has(this._defaultLocale)) { key = this._defaultLocale; } else { key = this._data.keys().next().value; } return [...(this._data.get(key) ?? [])]; }
  _resolveIncludes(item) {
    const resolved = { ...item };
    for (const field of this._includes) {
      const meta = this._relationMeta[field]; if (!meta) continue;
      const targets = Array.isArray(meta.target) ? meta.target : [meta.target];
      if (meta.multi) { const ids = item[field]; if (Array.isArray(ids)) { resolved[field] = ids.map(id => { if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, this._locale); if (r) return r; } return id; } if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, this._locale); if (r) return r; } return id; }); } }
      else { const id = item[field]; if (typeof id === 'string') { for (const t of targets) { const r = this._resolver(t, id, this._locale); if (r) { resolved[field] = r; break; } } } else if (typeof id === 'object' && id !== null && 'model' in id && 'ref' in id) { const r = this._resolver(id.model, id.ref, this._locale); if (r) resolved[field] = r; } }
    }
    return resolved;
  }
}

// ─── Data Registry ───

const _collectionRegistry = {
  'audit-event': new Map([
    ['en', _auditEventEn],
  ]),
  'billing-plan': new Map([
    ['en', _billingPlanEn],
  ]),
  'dashboard-stat': new Map([
    ['en', _dashboardStatEn],
  ]),
  'ops-notice': new Map([
    ['en', _opsNoticeEn],
  ]),
  'settings-group': new Map([
    ['en', _settingsGroupEn],
  ]),
  'work-queue-item': new Map([
    ['en', _workQueueItemEn],
  ]),
}

export function query(model) {
  const data = _collectionRegistry[model]
  if (!data) throw new Error(`Unknown collection model: "${model}"`)
  return new QueryBuilder(data, undefined, undefined, _defaultLocale)
}

const _singletonRegistry = {
  'dashboard-overview': new Map([
    ['en', _dashboardOverviewEn],
  ]),
  'footer': new Map([
    ['en', _footerEn],
  ]),
  'navigation': new Map([
    ['en', _navigationEn],
  ]),
  'seo-defaults': new Map([
    ['en', _seoDefaultsEn],
  ]),
  'site-settings': new Map([
    ['en', _siteSettingsEn],
  ]),
}

export function singleton(model) {
  const data = _singletonRegistry[model]
  if (!data) throw new Error(`Unknown singleton model: "${model}"`)
  return new SingletonAccessor(data, _defaultLocale)
}

const _dictionaryRegistry = {
  'ui-copy': new Map([
    ['en', _uiCopyEn],
  ]),
}

export function dictionary(model) {
  const data = _dictionaryRegistry[model]
  if (!data) throw new Error(`Unknown dictionary model: "${model}"`)
  return new DictionaryAccessor(data, _defaultLocale)
}

